### ISSUE TITLE
normPassphrase does not handle passwords with umlauts correctly

### ISSUE THREAD

**Issue by peterbitfly** [wealdtech/go-eth2-wallet-encryptor-keystorev4#2]
`normPassphrase("üöüöäöüöü")` will produce a different output compared to `norm.NFKD.String("üöüöäöüöü")`. Because of this the module is currently unable to decrypt keystores which were encrypted using a password that contains umlauts.

**Comment by mcdee** [comment]
Thank you for raising this issue.  It looks like the iterator is returning different results to the direct normalisation.

To confirm: when you talk about "keystores which were encrypted using a password that contains umlauts", do you mean those created with _other_ software or with this module?  The former is expected given the issue, the latter would be much more of a concern.

I have opened #3 to address this issue.  It retains existing functionality as a fallback, going with adherence to the standard first and back-compatibility second, although still ensuring that any keystore encrypted with the old method will still be decrypted by the call to `Decrypt()`.  Please could you give this a try and see if it fixes the issue?

**Comment by peterbitfly** [comment]
Thanks for your swift response. We only observed the issue when trying to import keystores generated with other tools. We did not create any keystores using this module.
